# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of Node.js.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - '*' # Run pipeline on all branches when pushed
  pull_request:
    branches:
      - '*' # Run pipeline on all branches when pushed

jobs:
  test:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: "Install MeteorJS"
      run: |
          curl https://install.meteor.com/ | sh
          export PATH=$PATH:/home/runner/.meteor

    - name: "Install dependencies"
      working-directory: ./code/beastly-brawl-showdown
      run: npm install

    - name: "Clean dependencies"
      working-directory: ./code/beastly-brawl-showdown
      run: npm ci

    - name: "Build source code"
      working-directory: ./code/beastly-brawl-showdown
      run: npm run build --if-present

    - name: "Run tests"
      working-directory: ./code/beastly-brawl-showdown
      run: npm test
