name: Tests for Simulator

env:
        SIM: code/simulator

on:
        push:
                paths:
                        - "$SIM/**"
                        - ".github/**"

jobs:
        static-analysis:
                runs-on: ubuntu-latest
                defaults:
                        run:
                                working-directory: $SIM
                steps:
                        - name: Checkout Code
                          uses: actions/checkout@v4
                          
                        - name: Set up Node.js
                          uses: actions/setup-node@v4
                          with:
                                  node-version: "22"
                        - name: Install dependencies
                          run: npm install
                          
                        - name: Run TypeScript type check
                          run: npx tsc --noEmit
